name: terraform

on: [pull_request]

jobs:
  fmt-check:
    runs-on: ubuntu-latest
    name: terraform fmt
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: terraform fmt
        uses: dflook/terraform-fmt-check@v1
        with:
          path: ./
